### ISSUE TITLE
IllegalArgumentException to getDocument

### ISSUE THREAD

**Issue by CraftSpider** [exbin/bined-intellij-plugin#30]
Version: PyCharm 2020.1 Beta
OS: Ubuntu 18.04
BinEd Version: Latest from plugin market

When I open a new file in BinEd, I get these errors. I'm also completely incapable of editing the file. Full stacktrace attached.

[stacktrace.txt](https://github.com/exbin/bined-intellij-plugin/files/4371310/stacktrace.txt)

**Comment by hajdam** [comment]
I was not able to reproduce this error, but it's possible I'm performing different method of opening. Can you clarify what method do you use to "open a new file"?

Version: PyCharm (tested also Community) 2020.1 Beta (201.6487.18 / Open JDK 11.0.6+8-b765.15 amd64)
OS: Fedora 31 x86_64
BinEd version: 0.2.2 (see about dialog via popup menu)

Also tested current development build (0.2.3.snapshot) which doesn't work, but due to different error.

**Comment by CraftSpider** [comment]
Ah, so: If I double click a file named `struct_test.bin`, it opens in BinEd then I get the errors. If I right click it and open as binary, it works just fine

**Comment by hajdam** [comment]
Association with .bin was suppose to be removed in issue #21 Not sure why it works again :-/ I'll take a look into it in next version.

**Comment by CraftSpider** [comment]
Alright. I would like if it was possible to associate the plugin and have it behave automatically, but I understand if it's too much of a maintenance hassle / unexpected behavior. Thank you for the help.

**Comment by hajdam** [comment]
Support for file type (Binary File) was added in 0.2.3. Hopefully it will work somehow, although file size is limited and performance may be affected in this mode.
And yes, it was quite a hassle :-)
